server:
  listenAddr: ":3000"

database:
  driver: "postgres"
  sqlite:
    file: "test.db"
  postgresql:
    host: "postgres"
    port: 5432
    dbName: "postgres"
    user: "postgres"
    password: "postgres"
    ssl: "disable"
    timezone: "UTC"
  autoMigrate: false

telegram:
  apiKey: ""
  webhookUrl: ""
  baseUrl: "https://api.telegram.org/bot%s/"
  endpointSetWebhook: "setWebhook"
  endpointSendMessage: "sendMessage"
  endpointSendPhoto: "sendPhoto"
  chatID: ""
