server:
  listenAddr: ":3000"

database:
  driver: "sqlite"
  sqlite:
    file: "test.db"
  postgresql:
    host: "127.0.0.1"
    port: 5432
    dbName: ""
    user: ""
    password: ""
    ssl: "disable"
    timezone: "UTC"
  autoMigrate: false

telegram:
  apiKey: ""
  webhookUrl: ""
  baseUrl: "https://api.telegram.org/bot%s/"
  endpointSetWebhook: "setWebhook"
  endpointSendMessage: "sendMessage"
  endpointSendPhoto: "sendPhoto"
  chatID: ""
